"""Collect [[slug]] reference markers from articles.tsv's md files into one TOML file.

For each md file (sorted by path) that has a Mathlog url in articles.tsv, its
per-article reference list refs/{ID}.toml is read and each [[slug]] marker
found in the md file is resolved to its full attribute set from that toml:
  - non-mathlog types: attributes (type, citation, url, accessed, author,
    site, journal, pages, year, publisher, ...) are taken directly
  - type "mathlog": same, plus an explicit "url" added by looking up the
    citation's title in articles.tsv to find the referenced article's own url

The output is grouped by slug rather than by file: each slug gets its own
[slug] heading with its merged attributes and a "files" list of every md
file that uses it. Since slugs are meant to be canonical across the whole
project, all attributes other than "citation"/"accessed" must match exactly
across every file that defines the same slug; a mismatch is a naming
collision. Every slug is checked before reporting — a conflict in one slug
never stops the scan of the rest, and refs.toml is still written (each
conflicting slug falls back to its definition with the latest "accessed"
date) — but afterward all conflicts found are printed together and the
command exits non-zero, so they can be fixed by hand in refs/{ID}.toml. The
"citation"/"accessed" fields are excluded from the conflict check itself
because they legitimately differ by export date.

Md files without a Mathlog url (and thus no refs/{ID}.toml) still contribute
their [[slug]] markers to the "files" list, unresolved. Files with no
[[slug]] markers are omitted.

Also writes refs-url.txt: urls referenced under more than one distinct slug
(the same source cited under different slug names across articles), sorted
by url, one line each as "url = slug, slug, ...".

Also writes refs-file.txt: for each md file that is itself a Mathlog article,
the distinct slugs other articles use to cite it via type = "mathlog"
(useful for spotting slug drift and picking one canonical slug per target
article), sorted by md path, one line each as "md_path = slug, slug, ..." or
"md_path = NONE" when no article cites it.

Also has a "check" subcommand: for each published article (one with a
refs/{ID}.toml), compares the [[slug]] markers used in the md body against
the keys defined in refs/{ID}.toml, and reports any mismatch — slugs used in
the body but not defined in the toml, and keys defined in the toml but not
used in the body.

"check" also confirms every file listed in md.tsv has a row in slugs.tsv (the
hand-maintained md path -> canonical slug ledger; see SLUG.md), reporting any
md.tsv file missing from it.

For unpublished articles (no Mathlog url yet, so no refs/{ID}.toml of their
own), "check" instead compares their [[slug]] markers against every slug
already known project-wide (the union of all published articles'
refs/{ID}.toml keys, refs-master.toml's keys, and slugs.tsv's reserved
slugs), reporting any that are undefined everywhere. This only catches
typos/not-yet-registered references (there's no per-file toml to also check
for "unused" slugs). slugs.tsv is what lets a [[slug]] citing a still-
unpublished sibling article resolve early, via that sibling's reserved
canonical slug, instead of waiting for it to be published.

The "check" subcommand also cross-checks refs.toml against refs-master.toml.
refs-master.toml is a hand-maintained subset covering all non-mathlog slugs
(mathlog entries are excluded since their citation data lives on Mathlog
itself); it stores a "title" field instead of "citation"/"accessed". For
every slug refs-master.toml defines, refs.toml must define the same slug,
its citation must imply the same title (via the same author/site/accessed/
url or journal/year/pages or publisher/year/pages stripping used to derive
titles for refs-master.toml), and every other shared field must match
exactly. Mismatches are printed; refs-master.toml itself is never
regenerated by this script.

Also has a "sync" subcommand: runs the same checks as "check", plus rewrites
each slug's "files" list in refs-master.toml to match refs.toml's, leaving
every other field (and refs-master.toml's own slug order/formatting)
untouched. Slugs missing from refs.toml are left alone (already reported as a
master mismatch by the check).

Also has a "show" subcommand: given one article (identified by its md path or
by its canonical slug from slugs.tsv), print the [[slug]] markers found in its
body in order of first appearance, and for each one, the entry from
refs-master.toml if defined there (preferred), else from refs.toml if it
carries any resolved attributes, else the md path from slugs.tsv's reverse
lookup if the slug is another (possibly unpublished) article's own canonical
slug (plus its Mathlog url from articles.tsv, if it's published), else a note
that no info was found.

Usage:
  refs_slugs.py build                      # write refs.toml only
  refs_slugs.py build -o out.toml
  refs_slugs.py build --url-output refs-url.txt --file-output refs-file.txt
  refs_slugs.py check
  refs_slugs.py sync
  refs_slugs.py show oct/01-octonion.md
  refs_slugs.py show 7shi-oct1
"""

from __future__ import annotations

import argparse
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ARTICLES_TSV = ROOT / "articles.tsv"
MD_TSV = ROOT / "md.tsv"
SLUGS_TSV = ROOT / "slugs.tsv"
REFS_DIR = ROOT / "refs"
DEFAULT_OUTPUT = ROOT / "refs.toml"
MASTER_PATH = ROOT / "refs-master.toml"
MATHLOG_BASE = "https://mathlog.info"

SLUG_RE = re.compile(r"\[\[([^\]]+)\]\]")
MATHLOG_CITATION_RE = re.compile(r"^([^,]+), (.*), Mathlog, ")


def load_md_entries(path: Path) -> list[tuple[Path, str]]:
    """Return (md_path, article_id) pairs; article_id is '' if none."""
    lines = path.read_text(encoding="utf-8").splitlines()
    entries: list[tuple[Path, str]] = []
    for line in lines[1:]:
        if not line.strip():
            continue
        cols = line.split("\t")
        url = cols[1] if len(cols) > 1 else ""
        md = cols[2] if len(cols) > 2 else ""
        if md:
            article_id = url.rsplit("/", 1)[-1] if url else ""
            entries.append((ROOT / md, article_id))
    return entries


def load_md_list(path: Path) -> list[str]:
    """Return every md path listed in md.tsv (the full article list, published
    or not), in file order."""
    lines = path.read_text(encoding="utf-8").splitlines()
    result: list[str] = []
    for line in lines[1:]:
        if not line.strip():
            continue
        md = line.split("\t")[0]
        if md:
            result.append(md)
    return result


def load_slugs_tsv(path: Path) -> dict[str, str]:
    """Return {md_path: slug} from slugs.tsv, the hand-maintained ledger of
    each article's canonical slug (used by other articles to cite it via
    [[slug]] even before it's published). "NONE" is kept as-is — it marks a
    file with no publication planned."""
    lines = path.read_text(encoding="utf-8").splitlines()
    result: dict[str, str] = {}
    for line in lines[1:]:
        if not line.strip():
            continue
        cols = line.split("\t")
        if len(cols) < 2:
            continue
        result[cols[0]] = cols[1]
    return result


def load_md_urls(path: Path) -> dict[str, str]:
    """Map md path (relative, as in articles.tsv) -> full Mathlog url, for
    every published article in articles.tsv."""
    lines = path.read_text(encoding="utf-8").splitlines()
    result: dict[str, str] = {}
    for line in lines[1:]:
        if not line.strip():
            continue
        cols = line.split("\t")
        if len(cols) < 3:
            continue
        url, md = cols[1], cols[2]
        if url and md:
            result[md] = MATHLOG_BASE + url
    return result


def load_title_urls(path: Path) -> dict[str, str]:
    """Map article title -> full Mathlog url, from articles.tsv."""
    lines = path.read_text(encoding="utf-8").splitlines()
    result: dict[str, str] = {}
    for line in lines[1:]:
        if not line.strip():
            continue
        cols = line.split("\t")
        if len(cols) < 4:
            continue
        _, url, _, title = cols[0], cols[1], cols[2], cols[3]
        if url and title:
            result[title] = MATHLOG_BASE + url
    return result


def load_refs_table(article_id: str) -> dict[str, dict]:
    refs_path = REFS_DIR / f"{article_id}.toml"
    if not refs_path.is_file():
        return {}
    with refs_path.open("rb") as f:
        return tomllib.load(f)


def resolve_slug(
    slug: str, refs_table: dict[str, dict], title_urls: dict[str, str]
) -> tuple[bool, dict]:
    """Return (defined, entry) for slug, with all attributes from refs/{ID}.toml.

    For type "mathlog", the citation's title is looked up in articles.tsv and
    the result is added as an explicit "url" key (refs/{ID}.toml itself has no
    url for mathlog entries).
    """
    entry = refs_table.get(slug)
    if entry is None:
        return False, {}
    entry = dict(entry)
    if entry.get("type") == "mathlog":
        m = MATHLOG_CITATION_RE.match(entry.get("citation", ""))
        if m:
            title = m.group(2)
            url = title_urls.get(title, "")
            if url:
                entry["url"] = url
    return True, entry


def collect_slugs_by_file(
    md_entries: list[tuple[Path, str]], title_urls: dict[str, str]
) -> list[tuple[Path, str, list[tuple[str, bool, dict]]]]:
    """Return (md_path, article_url, [(slug, defined, entry), ...]) per file."""
    result: list[tuple[Path, str, list[tuple[str, bool, dict]]]] = []
    for md_path, article_id in md_entries:
        text = md_path.read_text(encoding="utf-8")
        seen: set[str] = set()
        slugs: list[str] = []
        for slug in SLUG_RE.findall(text):
            if slug not in seen:
                seen.add(slug)
                slugs.append(slug)
        if not slugs:
            continue
        refs_table = load_refs_table(article_id) if article_id else {}
        resolved = [(slug, *resolve_slug(slug, refs_table, title_urls)) for slug in slugs]
        article_url = f"{MATHLOG_BASE}/articles/{article_id}" if article_id else ""
        result.append((md_path, article_url, resolved))
    result.sort(key=lambda e: e[0].relative_to(ROOT).as_posix())
    return result


def toml_string(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def toml_value(v) -> str:
    if isinstance(v, str):
        return toml_string(v)
    if isinstance(v, list):
        return "[" + ", ".join(toml_value(x) for x in v) + "]"
    return str(v)  # int, date: valid as-is in TOML


# Attributes that legitimately differ across refs/{ID}.toml exports of the
# same slug (the access date, and the citation string that embeds it) and so
# are excluded from the cross-file conflict check.
DATE_KEYS = {"citation", "accessed"}


def collect_by_slug(
    entries: list[tuple[Path, str, list[tuple[str, bool, dict]]]],
) -> tuple[dict[str, dict], list[str]]:
    """Group refs by slug into {slug: {**attrs, "files": [...]}}.

    All attributes other than DATE_KEYS must match exactly across every file
    that defines the slug; a mismatch is a naming collision. Every slug is
    checked before reporting, so a conflict in one slug never stops the scan
    of the rest — conflicting slugs are collected into the returned message
    list instead of being added to the result dict. Among the (otherwise
    identical) definitions of a slug with no conflict, the one with the
    latest "accessed" date is kept.
    """
    files_by_slug: dict[str, list[str]] = {}
    defs_by_slug: dict[str, list[tuple[str, dict]]] = {}
    for md_path, _, refs in entries:
        rel = md_path.relative_to(ROOT).as_posix()
        for slug, defined, entry in refs:
            files = files_by_slug.setdefault(slug, [])
            if rel not in files:
                files.append(rel)
            if defined:
                defs_by_slug.setdefault(slug, []).append((rel, entry))

    result: dict[str, dict] = {}
    conflicts: list[str] = []
    for slug, files in files_by_slug.items():
        files.sort()
        defs = defs_by_slug.get(slug, [])
        if not defs:
            result[slug] = {"files": files}
            continue

        base_rel, base_entry = defs[0]
        base_key = {k: v for k, v in base_entry.items() if k not in DATE_KEYS}
        mismatches = [
            (rel, entry)
            for rel, entry in defs[1:]
            if {k: v for k, v in entry.items() if k not in DATE_KEYS} != base_key
        ]
        if mismatches:
            lines = [f"slug conflict: {slug!r} differs across files (ignoring {sorted(DATE_KEYS)}):"]
            lines.append(f"  {base_rel}: {base_entry}")
            for rel, entry in mismatches:
                lines.append(f"  {rel}: {entry}")
            conflicts.append("\n".join(lines))
            # still merge below (latest "accessed" wins) so the build can
            # proceed; the conflict is reported, not silently ignored.

        chosen_rel, chosen_entry = base_rel, base_entry
        chosen_date = chosen_entry.get("accessed")
        for rel, entry in defs[1:]:
            date = entry.get("accessed")
            if date is not None and (chosen_date is None or date > chosen_date):
                chosen_rel, chosen_entry, chosen_date = rel, entry, date

        merged = dict(chosen_entry)
        merged["files"] = files
        result[slug] = merged
    return result, conflicts


def render_toml_by_slug(slug_map: dict[str, dict]) -> str:
    blocks: list[str] = []
    for slug in sorted(slug_map):
        entry = slug_map[slug]
        lines = [f"[{toml_string(slug)}]"]
        for key, value in entry.items():
            if key == "files":
                continue
            lines.append(f"{key} = {toml_value(value)}")
        items = ",\n".join(f"  {toml_string(f)}" for f in entry["files"])
        lines.append(f"files = [\n{items},\n]")
        blocks.append("\n".join(lines) + "\n")
    return "\n".join(blocks)


def find_shared_urls(entries: list[tuple[Path, str, list[tuple[str, bool, dict]]]]) -> list[tuple[str, list[str]]]:
    """Return (url, slugs) for urls cited under more than one distinct slug."""
    slugs_by_url: dict[str, list[str]] = {}
    for _, _, refs in entries:
        for slug, _, entry in refs:
            url = entry.get("url", "")
            if not url:
                continue
            slugs = slugs_by_url.setdefault(url, [])
            if slug not in slugs:
                slugs.append(slug)
    shared = [(url, slugs) for url, slugs in slugs_by_url.items() if len(slugs) > 1]
    shared.sort(key=lambda e: e[0])
    return shared


def render_shared_urls(shared: list[tuple[str, list[str]]]) -> str:
    return "".join(f"{url} = {', '.join(slugs)}\n" for url, slugs in shared)


def find_citing_slugs_by_file(
    md_entries: list[tuple[Path, str]],
    entries: list[tuple[Path, str, list[tuple[str, bool, dict]]]],
) -> list[tuple[Path, list[str]]]:
    """For each md file with an article id, the distinct slugs other
    articles use to cite it via type = "mathlog", sorted by md path."""
    id_to_path = {article_id: md_path for md_path, article_id in md_entries if article_id}
    slugs_by_id: dict[str, list[str]] = {aid: [] for aid in id_to_path}

    for _, _, refs in entries:
        for slug, _, entry in refs:
            url = entry.get("url", "")
            if entry.get("type") != "mathlog" or not url:
                continue
            article_id = url.rsplit("/", 1)[-1]
            if article_id not in slugs_by_id:
                continue
            slugs = slugs_by_id[article_id]
            if slug not in slugs:
                slugs.append(slug)

    result = [(md_path, slugs_by_id[aid]) for aid, md_path in id_to_path.items()]
    result.sort(key=lambda e: e[0].relative_to(ROOT).as_posix())
    return result


def render_citing_slugs(citing: list[tuple[Path, list[str]]]) -> str:
    lines = []
    for md_path, slugs in citing:
        key = md_path.relative_to(ROOT).as_posix()
        value = ", ".join(slugs) if slugs else "NONE"
        lines.append(f"{key} = {value}\n")
    return "".join(lines)


def find_slug_mismatches(
    md_entries: list[tuple[Path, str]],
) -> list[tuple[Path, str, list[str], list[str]]]:
    """For each published article (has refs/{ID}.toml), return (md_path,
    article_id, missing, unused) where missing = slugs used in the body but
    not defined in the toml, unused = toml keys not used in the body.
    Only entries with at least one mismatch are returned, sorted by md path.
    """
    result: list[tuple[Path, str, list[str], list[str]]] = []
    for md_path, article_id in md_entries:
        if not article_id:
            continue
        refs_path = REFS_DIR / f"{article_id}.toml"
        if not refs_path.is_file():
            continue
        refs_table = load_refs_table(article_id)
        text = md_path.read_text(encoding="utf-8")
        seen: set[str] = set()
        used: list[str] = []
        for slug in SLUG_RE.findall(text):
            if slug not in seen:
                seen.add(slug)
                used.append(slug)
        used_set = set(used)
        defined_set = set(refs_table.keys())
        missing = sorted(used_set - defined_set)
        unused = sorted(defined_set - used_set)
        if missing or unused:
            result.append((md_path, article_id, missing, unused))
    result.sort(key=lambda e: e[0].relative_to(ROOT).as_posix())
    return result


def render_mismatches(mismatches: list[tuple[Path, str, list[str], list[str]]]) -> str:
    lines: list[str] = []
    for md_path, article_id, missing, unused in mismatches:
        lines.append(f"== {md_path.relative_to(ROOT).as_posix()} ({article_id}) ==")
        if missing:
            lines.append(f"  未定義(本文にあるがtomlにない): {missing}")
        if unused:
            lines.append(f"  未使用(tomlにあるが本文にない): {unused}")
    return "\n".join(lines)


def find_missing_from_slugs_tsv(md_list: list[str], slugs_map: dict[str, str]) -> list[str]:
    """Return md.tsv paths that have no entry in slugs.tsv at all (not even
    "NONE"). slugs.tsv is meant to cover every file in md.tsv, so a missing
    entry means a new article hasn't been registered there yet."""
    return [md for md in md_list if md not in slugs_map]


def find_undefined_in_unpublished(
    md_entries: list[tuple[Path, str]], slugs_map: dict[str, str]
) -> list[tuple[Path, list[str]]]:
    """For each unpublished article (no Mathlog url, so no refs/{ID}.toml of
    its own), find [[slug]] markers in its body that aren't defined anywhere
    in the project — neither in any published article's refs/{ID}.toml, nor
    in refs-master.toml, nor as another article's reserved canonical slug in
    slugs.tsv. Unpublished articles have no refs/{ID}.toml of their own to
    check against, so this checks against every slug already known
    project-wide instead; it only catches typos and not-yet-registered
    references, not "unused" slugs (there is no per-file toml to compare
    against for that direction). slugs.tsv lets a [[slug]] citing a still-
    unpublished sibling article resolve early, via that sibling's reserved
    slug, rather than waiting for it to be published.
    """
    known: set[str] = set()
    for _, article_id in md_entries:
        if article_id:
            known |= load_refs_table(article_id).keys()
    if MASTER_PATH.is_file():
        with MASTER_PATH.open("rb") as f:
            known |= tomllib.load(f).keys()
    known |= {slug for slug in slugs_map.values() if slug != "NONE"}

    result: list[tuple[Path, list[str]]] = []
    for md_path, article_id in md_entries:
        if article_id:
            continue
        text = md_path.read_text(encoding="utf-8")
        seen: set[str] = set()
        used: list[str] = []
        for slug in SLUG_RE.findall(text):
            if slug not in seen:
                seen.add(slug)
                used.append(slug)
        undefined = sorted(set(used) - known)
        if undefined:
            result.append((md_path, undefined))
    result.sort(key=lambda e: e[0].relative_to(ROOT).as_posix())
    return result


def render_undefined_in_unpublished(entries: list[tuple[Path, list[str]]]) -> str:
    lines: list[str] = []
    for md_path, undefined in entries:
        lines.append(f"== {md_path.relative_to(ROOT).as_posix()} (未公開) ==")
        lines.append(f"  未定義(本文にあるがどこにも登録されていない): {undefined}")
    return "\n".join(lines)


def build_command(args: argparse.Namespace) -> None:
    args.output = args.output.resolve()
    if args.url_output is not None:
        args.url_output = args.url_output.resolve()
    if args.file_output is not None:
        args.file_output = args.file_output.resolve()

    md_entries = load_md_entries(ARTICLES_TSV)
    title_urls = load_title_urls(ARTICLES_TSV)
    entries = collect_slugs_by_file(md_entries, title_urls)
    slug_map, conflicts = collect_by_slug(entries)

    args.output.write_text(render_toml_by_slug(slug_map), encoding="utf-8")
    print(f"wrote {len(slug_map)} slugs to {args.output.relative_to(ROOT)}")

    if args.url_output is not None:
        shared = find_shared_urls(entries)
        args.url_output.write_text(render_shared_urls(shared), encoding="utf-8")
        print(f"wrote {len(shared)} shared urls to {args.url_output.relative_to(ROOT)}")

    if args.file_output is not None:
        citing = find_citing_slugs_by_file(md_entries, entries)
        args.file_output.write_text(render_citing_slugs(citing), encoding="utf-8")
        print(f"wrote {len(citing)} files to {args.file_output.relative_to(ROOT)}")

    if conflicts:
        print(f"\n{len(conflicts)} slug conflict(s) found (output written using latest \"accessed\" per slug anyway):\n")
        print("\n\n".join(conflicts))
        raise SystemExit(1)


def extract_title(entry: dict) -> str | None:
    """Derive the bibliographic title from a refs.toml entry's citation, by
    stripping the author prefix and the type-specific trailing fields
    (site/accessed/url for "website", journal/year/pages for "paper",
    publisher/year/pages for "book"). Returns None if the citation doesn't
    match the expected shape for its type. Used to check that refs.toml's
    citation agrees with refs-master.toml's hand-written "title" field.
    """
    citation = entry.get("citation")
    if citation is None:
        return None
    rem = citation
    author = entry.get("author")
    if author:
        prefix = ", ".join(author) + ", "
        if not rem.startswith(prefix):
            return None
        rem = rem[len(prefix) :]

    t = entry.get("type")
    suffix = ""
    if t == "website":
        tail_parts = []
        site = entry.get("site")
        if site:
            tail_parts.append(site)
        accessed = entry.get("accessed")
        if accessed is not None:
            tail_parts.append(f"閲覧日 {accessed.year}年{accessed.month}月{accessed.day}日")
        url = entry.get("url")
        if url:
            tail_parts.append(url)
        if tail_parts:
            suffix = ", " + ", ".join(tail_parts)
    elif t == "paper":
        journal = entry.get("journal")
        year = entry.get("year")
        tail_parts = [journal, str(year)]
        pages = entry.get("pages")
        if pages:
            tail_parts.append(str(pages))
        suffix = ", " + ", ".join(str(p) for p in tail_parts)
    elif t == "book":
        tail_parts = [entry.get("publisher"), str(entry.get("year")), str(entry.get("pages"))]
        suffix = ", " + ", ".join(str(p) for p in tail_parts)

    if suffix:
        if not rem.endswith(suffix):
            return None
        rem = rem[: -len(suffix)]
    return rem


# Fields present in refs.toml but not compared against refs-master.toml:
# "citation"/"accessed" have no counterpart there (replaced by "title"), and
# "files" is not required to stay in sync since refs-master.toml is
# hand-maintained rather than rebuilt from the articles.
MASTER_SKIP_KEYS = {"citation", "accessed", "files"}


def find_master_mismatches(refs: dict[str, dict], master: dict[str, dict]) -> list[str]:
    """Compare refs.toml against the hand-maintained refs-master.toml (the
    non-mathlog subset, keyed by the same slugs). Reports slugs missing from
    refs.toml, titles implied by refs.toml's citation that disagree with
    refs-master.toml's "title", and any other shared field that disagrees.

    A slug that refs.toml only knows as a body reference (an entry with just
    "files", no "citation") isn't resolved from any refs/{ID}.toml yet — e.g.
    it's cited only from an unpublished article. There's nothing to compare
    yet in that case, so it's skipped rather than reported as a mismatch on
    every field.
    """
    lines: list[str] = []
    for slug, m_entry in sorted(master.items()):
        r_entry = refs.get(slug)
        if r_entry is None:
            lines.append(f"master mismatch: {slug!r} defined in refs-master.toml but missing from refs.toml")
            continue
        if "citation" not in r_entry:
            continue

        title = extract_title(r_entry)
        m_title = m_entry.get("title")
        if title != m_title:
            lines.append(
                f"master mismatch: {slug!r} title differs: "
                f"refs.toml citation implies {title!r}, refs-master.toml has {m_title!r}"
            )

        for key, m_value in m_entry.items():
            if key in MASTER_SKIP_KEYS or key == "title":
                continue
            r_value = r_entry.get(key)
            if r_value != m_value:
                lines.append(
                    f"master mismatch: {slug!r} field {key!r} differs: "
                    f"refs.toml={r_value!r}, refs-master.toml={m_value!r}"
                )
    return lines


def sync_master_files(
    text: str, refs: dict[str, dict], master: dict[str, dict]
) -> tuple[str, list[str]]:
    """Rewrite each slug's "files = [...]" block in refs-master.toml's raw
    text to match refs.toml's "files" list for that slug, leaving every other
    field and the file's original slug order/formatting untouched. Slugs
    missing from refs.toml, or with no "files" key there, are left as-is
    (reported separately by find_master_mismatches). Returns the updated text
    and the list of slugs whose files list actually changed.
    """
    changed: list[str] = []
    for slug, m_entry in master.items():
        r_entry = refs.get(slug)
        if r_entry is None or "files" not in r_entry:
            continue
        new_files = r_entry["files"]
        if new_files == m_entry.get("files"):
            continue
        changed.append(slug)
        items = ",\n".join(f"  {toml_string(f)}" for f in new_files)
        new_block = f"files = [\n{items},\n]"
        pattern = re.compile(r'(\["' + re.escape(slug) + r'"\].*?)files = \[.*?\]', re.DOTALL)
        text = pattern.sub(lambda m: m.group(1) + new_block, text, count=1)
    return text, changed


def check_command(args: argparse.Namespace, sync: bool = False) -> None:
    md_entries = load_md_entries(ARTICLES_TSV)
    mismatches = find_slug_mismatches(md_entries)
    if not mismatches:
        print("mismatch nothing: all published articles match their refs/{ID}.toml")
    else:
        print(render_mismatches(mismatches))

    md_list = load_md_list(MD_TSV)
    slugs_map = load_slugs_tsv(SLUGS_TSV)
    missing_registrations = find_missing_from_slugs_tsv(md_list, slugs_map)
    if missing_registrations:
        print(f"未登録(md.tsvにあるがslugs.tsvにない): {missing_registrations}")
    else:
        print("registration nothing: every md.tsv file is registered in slugs.tsv")

    undefined = find_undefined_in_unpublished(md_entries, slugs_map)
    if undefined:
        print(render_undefined_in_unpublished(undefined))
    else:
        print("undefined nothing: all [[slug]] markers in unpublished articles are known project-wide")

    if not MASTER_PATH.is_file():
        return
    with DEFAULT_OUTPUT.open("rb") as f:
        refs = tomllib.load(f)
    with MASTER_PATH.open("rb") as f:
        master = tomllib.load(f)

    if sync:
        text = MASTER_PATH.read_text(encoding="utf-8")
        new_text, changed = sync_master_files(text, refs, master)
        if changed:
            MASTER_PATH.write_text(new_text, encoding="utf-8")
            print(f"synced files for {len(changed)} slug(s) in {MASTER_PATH.relative_to(ROOT)}: {changed}")
            with MASTER_PATH.open("rb") as f:
                master = tomllib.load(f)
        else:
            print("sync nothing: refs-master.toml files already match refs.toml")

    master_mismatches = find_master_mismatches(refs, master)
    if master_mismatches:
        print("\n".join(master_mismatches))
    else:
        print("master mismatch nothing: refs.toml agrees with refs-master.toml")


def sync_command(args: argparse.Namespace) -> None:
    check_command(args, sync=True)


def resolve_show_target(target: str, slugs_map: dict[str, str]) -> Path:
    """Resolve the "show" argument to an md path: if it names an existing
    file, use it directly; otherwise treat it as a canonical slug and look it
    up in slugs.tsv (md_path -> slug)."""
    candidate = ROOT / target
    if candidate.is_file():
        return candidate
    for md, slug in slugs_map.items():
        if slug == target:
            return ROOT / md
    raise SystemExit(f"error: {target!r} はファイルにもslugs.tsvのslugにも該当しません")


def extract_slugs_in_order(md_path: Path) -> list[str]:
    text = md_path.read_text(encoding="utf-8")
    seen: set[str] = set()
    result: list[str] = []
    for slug in SLUG_RE.findall(text):
        if slug not in seen:
            seen.add(slug)
            result.append(slug)
    return result


def has_resolved_info(entry: dict) -> bool:
    """True if a refs.toml entry carries anything beyond "files" (i.e. it was
    actually resolved from some refs/{ID}.toml, not just referenced)."""
    return any(k != "files" for k in entry)


def render_entry(entry: dict) -> str:
    lines = [f"  {key} = {toml_value(value)}" for key, value in entry.items() if key != "files"]
    return "\n".join(lines)


def build_slugs_reverse_map(slugs_map: dict[str, str]) -> dict[str, str]:
    """Return {slug: md_path} from slugs.tsv's {md_path: slug}, excluding
    "NONE" entries (files with no publication planned, so no canonical
    slug to reverse-lookup)."""
    return {slug: md for md, slug in slugs_map.items() if slug != "NONE"}


def show_command(args: argparse.Namespace) -> None:
    slugs_map = load_slugs_tsv(SLUGS_TSV)
    slugs_reverse = build_slugs_reverse_map(slugs_map)
    md_urls = load_md_urls(ARTICLES_TSV)
    md_path = resolve_show_target(args.target, slugs_map)
    md_rel = md_path.relative_to(ROOT).as_posix()
    slugs = extract_slugs_in_order(md_path)

    master: dict[str, dict] = {}
    if MASTER_PATH.is_file():
        with MASTER_PATH.open("rb") as f:
            master = tomllib.load(f)
    refs: dict[str, dict] = {}
    if DEFAULT_OUTPUT.is_file():
        with DEFAULT_OUTPUT.open("rb") as f:
            refs = tomllib.load(f)

    own_slug = slugs_map.get(md_rel)
    if own_slug is None:
        print(f"{md_rel} (slugs.tsvに未登録)")
    else:
        print(f"{md_rel} ({own_slug})")
    print(f"({len(slugs)} slugs)")
    for slug in slugs:
        if slug in master:
            print(f"[{slug}] (refs-master.toml)")
            print(render_entry(master[slug]))
        elif slug in refs and has_resolved_info(refs[slug]):
            print(f"[{slug}] (refs.toml)")
            print(render_entry(refs[slug]))
        elif slug in slugs_reverse:
            target_md = slugs_reverse[slug]
            print(f"[{slug}] (slugs.tsv)")
            print(f"  {target_md}")
            url = md_urls.get(target_md)
            if url:
                print(f"  url = {url}")
        else:
            print(f"[{slug}] 情報なし")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="write refs.toml (and optionally refs-url.txt/refs-file.txt)")
    build_parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    build_parser.add_argument("--url-output", type=Path, default=None)
    build_parser.add_argument("--file-output", type=Path, default=None)
    build_parser.set_defaults(func=build_command)

    check_parser = subparsers.add_parser(
        "check",
        help="check body [[slug]] markers against refs/{ID}.toml keys, "
        "unpublished articles against project-wide known slugs, "
        "and refs.toml against refs-master.toml",
    )
    check_parser.set_defaults(func=check_command)

    sync_parser = subparsers.add_parser(
        "sync",
        help="same checks as \"check\", plus sync each slug's \"files\" list in "
        "refs-master.toml to match refs.toml",
    )
    sync_parser.set_defaults(func=sync_command)

    show_parser = subparsers.add_parser(
        "show",
        help="show [[slug]] markers in one article, in order, with their refs.toml/refs-master.toml info",
    )
    show_parser.add_argument("target", help="md path or canonical slug (slugs.tsv)")
    show_parser.set_defaults(func=show_command)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
