"""Numerical checks for 07-s7.md.

The Cayley-Dickson construction reproducing the Graves-Cayley octonions
(triad table); norm multiplicativity |ab| = |a||b| for dims 1/2/4/8 and
its failure at dim 16; S^7 closed under multiplication with identity 1
and inverse o^*; the concrete failure of associativity
(e1 e2) e4 = e7 != e1 (e2 e4) = -e7; the inverse property
x^{-1}(x y) = y; the subalgebra generated by two elements being closed
and associative (Artin's theorem); the three Moufang identities;
Euler's formula exp(u theta) = cos theta + u sin theta, one-parameter
subgroups, and exp mapping Im O onto S^7; the exact two-factor
composition law (06's spherical cosine rule) surviving; failure of
associativity for three exponentials; the commutator closing on Im O
with [x,y] = 2 x cross y; the failure of the Jacobi identity
J(e1,e2,e4) = -12 e7, the general identity J(x,y,z) = -6 (x,y,z)
(associator), and its vanishing inside a triad; the Malcev identity;
conjugation rho_u unambiguous by alternativity, preserving Im O,
orthogonal, and a triple rotation for u = exp(e1 theta/2);
rho_p rho_q != rho_{pq} (and != rho_{qp}), with the composition having
unequal rotation angles so it is not any single conjugation; the Lie
algebra generated by the cross-product maps x -> u cross x having
dimension 21 = dim so(7); and unit-norm sedenion zero divisors.
"""

from itertools import combinations

import numpy as np

rng = np.random.default_rng(7)


def conj(a):
    c = -a
    c = c.copy()
    c[0] = a[0]
    return c


def mul(a, b):
    """Cayley-Dickson product: (a1,a2)(b1,b2) = (a1 b1 - b2* a2, b2 a1 + a2 b1*)."""
    n = len(a)
    if n == 1:
        return a * b
    h = n // 2
    a1, a2, b1, b2 = a[:h], a[h:], b[:h], b[h:]
    return np.concatenate([
        mul(a1, b1) - mul(conj(b2), a2),
        mul(b2, a1) + mul(a2, conj(b1)),
    ])


def basis(n, i):
    v = np.zeros(n)
    v[i] = 1.0
    return v


def norm(a):
    return np.sqrt(a @ a)


def im(a):
    b = a.copy()
    b[0] = 0.0
    return b


def rand(n=8):
    return rng.standard_normal(n)


def rand_unit_im(n=8):
    v = im(rand(n))
    return v / norm(v)


def comm(a, b):
    return mul(a, b) - mul(b, a)


def assoc(a, b, c):
    return mul(mul(a, b), c) - mul(a, mul(b, c))


def oexp(x):
    """exp of an octonion via Euler's formula (x = t + v, v imaginary)."""
    t, v = x[0], im(x)
    r = norm(v)
    u = v / r if r > 1e-12 else 0 * v
    e = basis(len(x), 0)
    return np.exp(t) * (np.cos(r) * e + np.sin(r) * u)


E = [basis(8, i) for i in range(8)]
ONE = E[0]
TRIADS = [(1, 2, 3), (1, 4, 5), (1, 7, 6), (2, 4, 6), (2, 5, 7), (3, 4, 7), (3, 6, 5)]

# Cayley-Dickson reproduces the Graves-Cayley multiplication table
ok = all(np.allclose(mul(E[i], E[i]), -ONE) for i in range(1, 8))
for a, b, c in TRIADS:
    ok &= np.allclose(mul(E[a], E[b]), E[c])
    ok &= np.allclose(mul(E[b], E[c]), E[a])
    ok &= np.allclose(mul(E[c], E[a]), E[b])
    ok &= np.allclose(mul(E[b], E[a]), -E[c])
print("Cayley-Dickson reproduces Graves-Cayley triads:", ok)

# Norm multiplicativity in dims 1, 2, 4, 8; failure in dim 16
ok = True
for n in (1, 2, 4, 8):
    for _ in range(20):
        a, b = rand(n), rand(n)
        ok &= np.isclose(norm(mul(a, b)), norm(a) * norm(b))
print("|ab| = |a||b| in dims 1, 2, 4, 8:", ok)
fails = 0
for _ in range(20):
    a, b = rand(16), rand(16)
    fails += not np.isclose(norm(mul(a, b)), norm(a) * norm(b))
print("|ab| = |a||b| fails in dim 16:", fails > 0, f"({fails}/20 random pairs)")

# S^7: closed under product, identity, inverse = conjugate
ok = True
for _ in range(20):
    o, p = rand(), rand()
    o, p = o / norm(o), p / norm(p)
    ok &= np.isclose(norm(mul(o, p)), 1)
    ok &= np.allclose(mul(o, ONE), o) and np.allclose(mul(ONE, o), o)
    ok &= np.allclose(mul(o, conj(o)), ONE) and np.allclose(mul(conj(o), o), ONE)
print("S^7 closed, 1 is identity, o^* is inverse:", ok)

# Associativity failure on basis elements of S^7
print("(e1 e2) e4 = e7:", np.allclose(mul(mul(E[1], E[2]), E[4]), E[7]),
      "/ e1 (e2 e4) = -e7:", np.allclose(mul(E[1], mul(E[2], E[4])), -E[7]))

# Inverse property x^{-1}(x y) = y, (y x) x^{-1} = y
ok = True
for _ in range(20):
    x, y = rand(), rand()
    xinv = conj(x) / (x @ x)
    ok &= np.allclose(mul(xinv, mul(x, y)), y)
    ok &= np.allclose(mul(mul(y, x), xinv), y)
print("inverse property x^-1(xy) = y, (yx)x^-1 = y:", ok)

# Artin: the subalgebra spanned by {1, x, y, xy} is closed and associative
ok = True
for _ in range(10):
    x, y = rand(), rand()
    B = np.array([ONE, x, y, mul(x, y)])
    closed = True
    for a in B:
        for b in B:
            p = mul(a, b)
            coef, res, *_ = np.linalg.lstsq(B.T, p, rcond=None)
            closed &= np.allclose(B.T @ coef, p)
    ok &= closed
    for _ in range(5):
        a, b, c = (rng.standard_normal(4) @ B for _ in range(3))
        ok &= np.allclose(assoc(a, b, c), 0)
print("span{1, x, y, xy} closed and associative (Artin):", ok)

# Moufang identities
ok = True
for _ in range(20):
    x, y, z = rand(), rand(), rand()
    zxz = mul(mul(z, x), z)
    ok &= np.allclose(mul(z, mul(x, mul(z, y))), mul(zxz, y))
    ok &= np.allclose(mul(mul(mul(x, z), y), z), mul(x, mul(z, mul(y, z))))
    ok &= np.allclose(mul(mul(z, x), mul(y, z)), mul(mul(z, mul(x, y)), z))
    ok &= np.allclose(mul(mul(z, x), mul(y, z)), mul(z, mul(mul(x, y), z)))
print("Moufang identities:", ok)

# Euler's formula and one-parameter subgroups
ok = True
for _ in range(10):
    u = rand_unit_im()
    t1, t2 = rng.uniform(-2, 2, 2)
    s, term = np.zeros(8), ONE.copy()
    for k in range(1, 40):
        s = s + term
        term = mul(term, u * t1) / k
    ok &= np.allclose(s, np.cos(t1) * ONE + np.sin(t1) * u)
    ok &= np.allclose(mul(oexp(u * t1), oexp(u * t2)), oexp(u * (t1 + t2)))
print("exp(u t) = cos t + u sin t, one-parameter subgroup:", ok)

# exp: Im O -> S^7 is onto
ok = True
for _ in range(10):
    o = rand()
    o /= norm(o)
    t = np.arccos(np.clip(o[0], -1, 1))
    v = im(o)
    u = v / norm(v)
    ok &= np.allclose(oexp(u * t), o)
print("every unit octonion is exp(u t):", ok)

# Two-factor composition law (06's exact formula) survives
ok = True
for _ in range(10):
    u, v = rand_unit_im(), rand_unit_im()
    a, b = rng.uniform(0.1, 1.5, 2)
    lhs = mul(oexp(u * a), oexp(v * b))
    cross = im(mul(u, v))
    dot = -mul(u, v)[0]
    rhs = (np.cos(a) * np.cos(b) - dot * np.sin(a) * np.sin(b)) * ONE \
        + np.sin(a) * np.cos(b) * u + np.cos(a) * np.sin(b) * v \
        + np.sin(a) * np.sin(b) * cross
    ok &= np.allclose(lhs, rhs)
print("exact two-factor composition law:", ok)

# Three exponentials: associativity fails
A, B, C = oexp(E[1] * np.pi / 4), oexp(E[2] * np.pi / 4), oexp(E[4] * np.pi / 4)
print("(exp exp) exp != exp (exp exp):",
      not np.allclose(mul(mul(A, B), C), mul(A, mul(B, C))))

# Commutator closes on Im O and equals twice the 7-dim cross product
ok = True
for _ in range(20):
    x, y = im(rand()), im(rand())
    c = comm(x, y)
    ok &= np.isclose(c[0], 0)
    ok &= np.allclose(c, 2 * im(mul(x, y)))
print("[x,y] imaginary and = 2 (x cross y):", ok)

# Jacobi identity fails: J(e1,e2,e4) = -12 e7; J(x,y,z) = -6 (x,y,z)
def jacobi(x, y, z):
    return comm(x, comm(y, z)) + comm(y, comm(z, x)) + comm(z, comm(x, y))

print("J(e1,e2,e4) = -12 e7:", np.allclose(jacobi(E[1], E[2], E[4]), -12 * E[7]))
ok = True
for _ in range(20):
    x, y, z = rand(), rand(), rand()
    ok &= np.allclose(jacobi(x, y, z), -6 * assoc(x, y, z))
print("J(x,y,z) = -6 [(xy)z - x(yz)]:", ok)
ok = True
for _ in range(10):
    a, b, c = TRIADS[rng.integers(len(TRIADS))]
    Bq = np.array([ONE, E[a], E[b], E[c]])
    x, y, z = (rng.standard_normal(4) @ Bq for _ in range(3))
    ok &= np.allclose(jacobi(x, y, z), 0)
print("J = 0 inside a triad (quaternionic subalgebra):", ok)

# Malcev identity: J(x, y, [x,z]) = [J(x,y,z), x]
ok = True
for _ in range(20):
    x, y, z = im(rand()), im(rand()), im(rand())
    ok &= np.allclose(jacobi(x, y, comm(x, z)), comm(jacobi(x, y, z), x))
print("Malcev identity J(x,y,[x,z]) = [J(x,y,z),x]:", ok)

# Conjugation rho_u: unambiguous, preserves Im O, orthogonal
def rho_matrix(u):
    uinv = conj(u) / (u @ u)
    R = np.zeros((7, 7))
    for j in range(7):
        R[:, j] = mul(mul(u, E[j + 1]), uinv)[1:]
    return R

ok = True
for _ in range(20):
    u, x = rand(), rand()
    uinv = conj(u) / (u @ u)
    ok &= np.allclose(mul(mul(u, x), uinv), mul(u, mul(x, uinv)))
    ok &= np.isclose(mul(mul(u, im(x)), uinv)[0], 0)
print("(ux)u^-1 = u(xu^-1), Im O preserved:", ok)
u = rand()
u /= norm(u)
R = rho_matrix(u)
print("rho_u orthogonal with det 1:",
      np.allclose(R.T @ R, np.eye(7)) and np.isclose(np.linalg.det(R), 1))

# Triple rotation: conjugation by exp(e1 theta/2) rotates the three planes
# (e2,e3), (e4,e5), (e7,e6) by theta and fixes e1
theta = 0.9
R = rho_matrix(oexp(E[1] * theta / 2))
c, s = np.cos(theta), np.sin(theta)
T = np.zeros((7, 7))
T[0, 0] = 1
for (i, j) in ((2, 3), (4, 5), (7, 6)):
    T[i - 1, i - 1] = T[j - 1, j - 1] = c
    T[j - 1, i - 1] = s
    T[i - 1, j - 1] = -s
print("rho_exp(e1 t/2) = triple rotation by t in planes (2,3),(4,5),(7,6):",
      np.allclose(R, T))

# rho is not a homomorphism: rho_p rho_q != rho_{pq}, rho_{qp}
p, q = oexp(E[1] * 0.3), oexp(E[2] * 0.5)
Rp, Rq, Rpq, Rqp = rho_matrix(p), rho_matrix(q), rho_matrix(mul(p, q)), rho_matrix(mul(q, p))
print("rho_p rho_q != rho_pq and != rho_qp:",
      not np.allclose(Rp @ Rq, Rpq) and not np.allclose(Rp @ Rq, Rqp))

# ... and the composition is not any single conjugation: a triple rotation
# has eigenvalues {1, e^{+-i t} (x3)}, but rho_p rho_q has unequal angles
angles = np.sort(np.abs(np.angle(np.linalg.eigvals(Rp @ Rq))))
print("rho_p rho_q rotation angles unequal (not a triple rotation):",
      angles[6] - angles[1] > 1e-6, np.round(angles[1::2], 4))

# rho_u is generally not an automorphism: rho_u(xy) != rho_u(x) rho_u(y)
u = oexp(E[1] * 0.4)
x, y = rand(), rand()
uinv = conj(u)
lhs = mul(mul(u, mul(x, y)), uinv)
rhs = mul(mul(mul(u, x), uinv), mul(mul(u, y), uinv))
print("rho_u(xy) != rho_u(x) rho_u(y) in general:", not np.allclose(lhs, rhs))

# The cross-product maps x -> u cross x generate all of so(7) (dim 21)
def lie_closure(mats):
    elems = []
    def rank(ms):
        return np.linalg.matrix_rank(np.array([m.flatten() for m in ms]))
    for m in mats:
        if not elems or rank(elems + [m]) > rank(elems):
            elems.append(m)
    grown = True
    while grown:
        grown = False
        for i in range(len(elems)):
            for j in range(i + 1, len(elems)):
                br = elems[i] @ elems[j] - elems[j] @ elems[i]
                if rank(elems + [br]) > rank(elems):
                    elems.append(br)
                    grown = True
    return elems

C = []
for i in range(1, 8):
    M = np.zeros((7, 7))
    for j in range(7):
        M[:, j] = im(mul(E[i], E[j + 1]))[1:]
    C.append(M)
closure = lie_closure(C)
print("Lie closure of cross maps: dim =", len(closure),
      "= dim so(7):", len(closure) == 21,
      "/ all antisymmetric:", all(np.allclose(M.T, -M) for M in closure))

# Sedenions: unit-norm zero divisors (e_a + e_b)(e_c + e_d) = 0
E16 = [basis(16, i) for i in range(16)]
found = []
for (a, b) in combinations(range(1, 16), 2):
    for (c, d) in combinations(range(1, 16), 2):
        for t in (1, -1):
            p = E16[a] + E16[b]
            q = E16[c] + t * E16[d]
            if np.allclose(mul(p, q), 0):
                found.append((a, b, c, t, d))
print("sedenion zero divisors (e_a+e_b)(e_c±e_d)=0:", len(found), "pairs, e.g.",
      [f"(e{a}+e{b})(e{c}{'+' if t > 0 else '-'}e{d})" for a, b, c, t, d in found[:4]])
