[nakajima-4d-rot]
type = "website"
citation = "中嶋 慧, 4次元回転と四元数, 閲覧日 2026年7月20日, https://cf096240.cloudfree.jp/4D_rotation.pdf"
url = "https://cf096240.cloudfree.jp/4D_rotation.pdf"
accessed = 2026-07-20
author = ["中嶋 慧"]
