[7shi-h]
type = "mathlog"
citation = "7shi, 四元数とホップファイブレーション 1 四元数からの生成, Mathlog, Tue May 14 2024, アクセス日: Sun Jul 19 2026"

[7shi-s]
type = "mathlog"
citation = "7shi, 四元数とホップファイブレーション 2 スピノルのテンソル積, Mathlog, Fri May 24 2024, アクセス日: Sun Jul 19 2026"

[7shi-bq]
type = "mathlog"
citation = "7shi, パウリ行列と四元数：双四元数による橋渡し, Mathlog, Thu Jul 11 2024, アクセス日: Sun Jul 19 2026"
