[7shi-lie2]
type = "mathlog"
citation = "7shi, リー群・リー代数の初歩 2 四元数とSU(2), Mathlog, Fri Jul 10 2026, アクセス日: Fri Jul 24 2026"

[7shi-bloch]
type = "mathlog"
citation = "7shi, 四元数とホップファイブレーション 3 ブロッホ球と密度行列, Mathlog, Wed Jul 15 2026, アクセス日: Fri Jul 24 2026"

[7shi-h]
type = "mathlog"
citation = "7shi, 四元数とホップファイブレーション 1 四元数からの生成, Mathlog, Tue May 14 2024, アクセス日: Fri Jul 24 2026"

[7shi-mir]
type = "mathlog"
citation = "7shi, 鏡映：ベクトルから八元数まで, Mathlog, Tue Jul 16 2024, アクセス日: Fri Jul 24 2026"
