"""Checks for 06-clifford-gates.md (single-qubit part).

Verifies numerically (random variables, numpy):

1. Conjugation by R_n(θ) = cos(θ/2)I - i sin(θ/2) n·σ acts on the Bloch
   vector as the Rodrigues rotation matrix (right-handed, angle θ about n).
2. Rotor decompositions U = e^{iφ} R_n(θ) for the six gates:
   X = iR_x(π), Y = iR_y(π), Z = iR_z(π), H = iR_{(x+z)/√2}(π),
   S = e^{iπ/4} R_z(π/2), T = e^{iπ/8} R_z(π/4).
3. Sandwich formula (n·σ)(r·σ)(n·σ) = {2(n·r)n - r}·σ.
4. The Pauli group P1 = {i^k P} has order 16 and is closed under
   multiplication; mod phase its Bloch action is the Klein four-group;
   P1 ∩ SU(2) = {±I, ±iσ} corresponds to the quaternion group Q8
   under 1 ≅ I, i ≅ -iσ_x, j ≅ -iσ_y, k ≅ -iσ_z.
5. H and S act on the Bloch vector as signed permutations
   (S: (x,y,z) ↦ (-y,x,z), H: x ↔ z, y ↦ -y); the group generated by
   R(H), R(S) is exactly the 24 signed permutation matrices with det +1
   (rotation group of the octahedron); ⟨H, S⟩ mod phase also has order 24;
   S and HSH are 4-fold rotations about z and x, HS has order 3.
6. The six states |0>, |1>, |±>, |±i> have Bloch vectors ±z, ±x, ±y,
   and form a single orbit of ⟨H, S⟩ mod phase.
7. T is not Clifford: T X T† = (σ_x + σ_y)/√2 is not a signed Pauli axis,
   and R(T) does not preserve the octahedron's vertex set.
"""

import numpy as np

rng = np.random.default_rng(42)

I2 = np.eye(2, dtype=complex)
sx = np.array([[0, 1], [1, 0]], dtype=complex)
sy = np.array([[0, -1j], [1j, 0]])
sz = np.array([[1, 0], [0, -1]], dtype=complex)
paulis = [sx, sy, sz]

H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
S = np.diag([1, 1j])
T = np.diag([1, np.exp(1j * np.pi / 4)])

def ns(n):
    return sum(n[i] * paulis[i] for i in range(3))

def rotor(n, theta):
    return np.cos(theta / 2) * I2 - 1j * np.sin(theta / 2) * ns(n)

def conj_so3(U):
    # 3x3 matrix M with U (r·σ) U† = (M r)·σ
    M = np.empty((3, 3))
    for a in range(3):
        img = U @ paulis[a] @ U.conj().T
        for b in range(3):
            M[b, a] = np.trace(paulis[b] @ img).real / 2
    return M

def rodrigues(n, theta):
    n = np.asarray(n, dtype=float)
    K = np.array([[0, -n[2], n[1]], [n[2], 0, -n[0]], [-n[1], n[0], 0]])
    return np.cos(theta) * np.eye(3) + np.sin(theta) * K \
        + (1 - np.cos(theta)) * np.outer(n, n)

def rand_axis():
    n = rng.normal(size=3)
    return n / np.linalg.norm(n)

def canon(U):
    # remove the global phase: make the first nonzero entry real positive
    u = U.flatten()
    u0 = u[np.argmax(np.abs(u) > 1e-8)]
    return U * (u0.conjugate() / abs(u0))

def key(M):
    return tuple(np.round(M, 6).flatten().tolist())

def closure(gens, canonicalize=lambda M: M):
    # BFS over products of the generators
    e = canonicalize(np.eye(gens[0].shape[0], dtype=gens[0].dtype))
    pool = {key(e): e}
    for g in gens:
        g = canonicalize(g)
        pool[key(g)] = g
    while True:
        new = {}
        for a in pool.values():
            for g in gens:
                p = canonicalize(a @ g)
                if key(p) not in pool:
                    new[key(p)] = p
        if not new:
            return list(pool.values())
        pool.update(new)

def check_rotor_conjugation():
    for _ in range(50):
        n, theta = rand_axis(), rng.uniform(0, 2 * np.pi)
        assert np.allclose(conj_so3(rotor(n, theta)), rodrigues(n, theta))
    # explicit orientation: θ about z sends σ_x to cos θ σ_x + sin θ σ_y
    theta = rng.uniform(0, 2 * np.pi)
    U = rotor([0, 0, 1], theta)
    assert np.allclose(U @ sx @ U.conj().T, np.cos(theta) * sx + np.sin(theta) * sy)

def check_gate_decompositions():
    ez = [0, 0, 1]
    cases = [
        (sx, 1j, [1, 0, 0], np.pi),
        (sy, 1j, [0, 1, 0], np.pi),
        (sz, 1j, ez, np.pi),
        (H, 1j, np.array([1, 0, 1]) / np.sqrt(2), np.pi),
        (S, np.exp(1j * np.pi / 4), ez, np.pi / 2),
        (T, np.exp(1j * np.pi / 8), ez, np.pi / 4),
    ]
    for U, phase, n, theta in cases:
        assert np.allclose(U, phase * rotor(n, theta))

def check_sandwich():
    for _ in range(50):
        n = rand_axis()
        r = rng.normal(size=3)
        lhs = ns(n) @ ns(r) @ ns(n)
        rhs = ns(2 * np.dot(n, r) * n - r)
        assert np.allclose(lhs, rhs)

def check_pauli_group():
    base = [I2, sx, sy, sz]
    P1 = [1j**k * P for k in range(4) for P in base]
    assert len(P1) == 16
    # closed under multiplication
    for a in P1:
        for b in P1:
            assert any(np.allclose(a @ b, c) for c in P1)
    # mod phase: the Bloch actions form the Klein four-group
    actions = []
    for a in P1:
        M = conj_so3(a)
        if not any(np.allclose(M, N) for N in actions):
            actions.append(M)
    expected = [np.diag(d) for d in
                ([1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, 1.])]
    assert len(actions) == 4
    for M in actions:
        assert any(np.allclose(M, N) for N in expected)
    # P1 ∩ SU(2) = {±I, ±iσ} ≅ Q8
    su2 = [g for g in P1 if np.isclose(np.linalg.det(g), 1)]
    assert len(su2) == 8
    units = [s * v for s in (1, -1)
             for v in (np.eye(4)[0], np.eye(4)[1], np.eye(4)[2], np.eye(4)[3])]
    def qmul(a, b):
        w1, x1, y1, z1 = a
        w2, x2, y2, z2 = b
        return np.array([
            w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
            w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
            w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
            w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2])
    def phi(q):
        # 1 ≅ I, i ≅ -iσ_x, j ≅ -iσ_y, k ≅ -iσ_z
        return q[0] * I2 - 1j * (q[1] * sx + q[2] * sy + q[3] * sz)
    # phi is a homomorphism on Q8 and maps Q8 onto P1 ∩ SU(2)
    for a in units:
        for b in units:
            assert np.allclose(phi(qmul(a, b)), phi(a) @ phi(b))
    images = [phi(u) for u in units]
    for g in su2:
        assert any(np.allclose(g, m) for m in images)

def check_h_s_octahedral():
    RH, RS = conj_so3(H), conj_so3(S)
    # S: (x,y,z) ↦ (-y,x,z),  H: x ↔ z, y ↦ -y
    assert np.allclose(RS, np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]]))
    assert np.allclose(RH, np.array([[0, 0, 1], [0, -1, 0], [1, 0, 0]]))
    # S and HSH are 4-fold rotations about z and x, HS has order 3
    assert np.allclose(np.linalg.matrix_power(RS, 4), np.eye(3))
    assert not np.allclose(np.linalg.matrix_power(RS, 2), np.eye(3))
    RHSH = RH @ RS @ RH
    assert np.allclose(RHSH, rodrigues([1, 0, 0], np.pi / 2))
    assert np.allclose(np.linalg.matrix_power(RH @ RS, 3), np.eye(3))
    # closure = all 24 signed permutation matrices with det +1
    group = closure([RH, RS])
    assert len(group) == 24
    for M in group:
        assert np.allclose(np.abs(M) * (np.abs(M) > 0.5), np.abs(M))  # entries 0, ±1
        assert np.allclose((np.abs(M) > 0.5).sum(axis=0), 1)
        assert np.allclose((np.abs(M) > 0.5).sum(axis=1), 1)
        assert np.isclose(np.linalg.det(M), 1)
    # ⟨H, S⟩ mod phase also has order 24
    ugroup = closure([H, S], canonicalize=canon)
    assert len(ugroup) == 24

def check_six_states():
    s2 = np.sqrt(2)
    states = {
        (0, 0, 1): np.array([1, 0], dtype=complex),          # |0>
        (0, 0, -1): np.array([0, 1], dtype=complex),         # |1>
        (1, 0, 0): np.array([1, 1]) / s2,                    # |+>
        (-1, 0, 0): np.array([1, -1]) / s2,                  # |->
        (0, 1, 0): np.array([1, 1j]) / s2,                   # |+i>
        (0, -1, 0): np.array([1, -1j]) / s2,                 # |-i>
    }
    for r, psi in states.items():
        bloch = [np.real(psi.conj() @ s @ psi) for s in paulis]
        assert np.allclose(bloch, r)
    # single orbit of ⟨H, S⟩ mod phase
    def skey(psi):
        u0 = psi[np.argmax(np.abs(psi) > 1e-8)]
        return tuple(np.round(psi * u0.conjugate() / abs(u0), 6).tolist())
    ugroup = closure([H, S], canonicalize=canon)
    orbit = {skey(U @ np.array([1, 0], dtype=complex)) for U in ugroup}
    assert len(orbit) == 6
    assert orbit == {skey(psi) for psi in states.values()}

def check_t_not_clifford():
    img = T @ sx @ T.conj().T
    assert np.allclose(img, (sx + sy) / np.sqrt(2))
    # not proportional to any Pauli with factor ±1, ±i
    for P in paulis:
        for c in (1, -1, 1j, -1j):
            assert not np.allclose(img, c * P)
    # R(T) does not preserve the vertex set {±e_1, ±e_2, ±e_3}
    RT = conj_so3(T)
    vertices = [s * np.eye(3)[i] for s in (1, -1) for i in range(3)]
    moved = RT @ np.array([1, 0, 0])
    assert not any(np.allclose(moved, v) for v in vertices)

if __name__ == "__main__":
    check_rotor_conjugation()
    check_gate_decompositions()
    check_sandwich()
    check_pauli_group()
    check_h_s_octahedral()
    check_six_states()
    check_t_not_clifford()
    print("check-06-single-qubit: all checks passed")
