"""Checks for 07-real-qubit.md (single-qubit part).

Verifies numerically (random variables, numpy):

1. For a real state Ψ = (α, β) the Bloch vector is (2αβ, 0, α²-β²):
   the y component vanishes identically, and the surviving pair (x, z)
   is exactly the real Hopf map H_R(α, β) = (2αβ, α²-β²).
2. Ψ(θ) = (cos θ, sin θ) and -Ψ(θ) share one image, the image angle is 2θ,
   and z + i x equals ζ² for ζ = α + β i (the fiber S⁰ = {±1}).
3. The first row of ρ = ΨΨ^T is (α², αβ) = ((1+z)/2, x/2), a circle of
   radius 1/2 centered at (1/2, 0).
4. Born rule in the plane: p± = (1 ± r·n)/2 = (Ψ±^T Ψ)² = cos²/sin² of the
   half angle, for n = (sin φ, 0, cos φ) and real eigenstates Ψ±.
5. X, Z, H are reflections (det = -1) about the lines at 45°, 0°, 22.5°;
   the O(2) action on the total space descends 2-to-1 onto O(2) of the base
   (rotation θ ↦ 2θ, reflection φ ↦ 2φ) with kernel {±I} = the fiber.
6. The real Pauli group {±I, ±X, ±Z, ±XZ} has order 8, is closed, and has
   five elements of order 2, hence is D4, not Q8 (which has exactly one).
7. The normalizer of the real Pauli group in O(2) is exactly the 16 elements
   R(45°k), F(22.5°k); mod phase it has order 8 (symmetries of the square),
   is generated by H and Z, and its Bloch action is the index-3 subgroup of
   the 24 octahedral rotations that preserves the y = 0 plane.
8. S and T are excluded because their Bloch action does not preserve the
   y = 0 plane (S maps x to y).
"""

import numpy as np

rng = np.random.default_rng(42)

I2 = np.eye(2, dtype=complex)
sx = np.array([[0, 1], [1, 0]], dtype=complex)
sy = np.array([[0, -1j], [1j, 0]])
sz = np.array([[1, 0], [0, -1]], dtype=complex)
paulis = [sx, sy, sz]

X = sx.real
Z = sz.real
H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
S = np.diag([1, 1j])
T = np.diag([1, np.exp(1j * np.pi / 4)])

def state(theta):
    return np.array([np.cos(theta), np.sin(theta)])

def bloch(psi):
    psi = np.asarray(psi, dtype=complex)
    return np.array([np.real(psi.conj() @ s @ psi) for s in paulis])

def hopf_r(psi):
    a, b = psi
    return np.array([2 * a * b, a**2 - b**2])

def rot2(theta):
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s], [s, c]])

def refl2(phi):
    c, s = np.cos(2 * phi), np.sin(2 * phi)
    return np.array([[c, s], [s, -c]])

def conj_so3(U):
    # 3x3 matrix M with U (r·σ) U† = (M r)·σ
    M = np.empty((3, 3))
    for a in range(3):
        img = U @ paulis[a] @ U.conj().T
        for b in range(3):
            M[b, a] = np.trace(paulis[b] @ img).real / 2
    return M

def base_action(g):
    # the Bloch action restricted to the y = 0 plane, in (z, x) coordinates
    M = conj_so3(g.astype(complex))
    assert np.allclose(M[1, [0, 2]], 0) and np.allclose(M[[0, 2], 1], 0)
    return M[np.ix_([2, 0], [2, 0])]

def key(M):
    return tuple(np.round(M, 6).flatten().tolist())

def closure(gens, canonicalize=lambda M: M):
    e = canonicalize(np.eye(gens[0].shape[0], dtype=gens[0].dtype))
    pool = {key(e): e}
    for g in gens:
        g = canonicalize(g)
        pool[key(g)] = g
    while True:
        new = {}
        for a in pool.values():
            for g in gens:
                p = canonicalize(a @ g)
                if key(p) not in pool:
                    new[key(p)] = p
        if not new:
            return list(pool.values())
        pool.update(new)

def sign_canon(M):
    # remove the global sign: make the first nonzero entry positive
    m = M.flatten()
    return M * np.sign(m[np.argmax(np.abs(m) > 1e-8)].real)

def check_bloch_restriction():
    for _ in range(100):
        psi = state(rng.uniform(0, 2 * np.pi))
        r = bloch(psi)
        assert np.isclose(r[1], 0)                     # y vanishes
        assert np.allclose(r[[0, 2]], hopf_r(psi))     # (x, z) = H_R
        assert np.isclose(np.linalg.norm(r), 1)        # great circle of S²

def check_double_cover():
    for _ in range(100):
        theta = rng.uniform(0, 2 * np.pi)
        psi = state(theta)
        assert np.allclose(hopf_r(psi), hopf_r(-psi))  # fiber S⁰ = {±1}
        x, z = hopf_r(psi)
        assert np.allclose([z, x], [np.cos(2 * theta), np.sin(2 * theta)])
        zeta = psi[0] + 1j * psi[1]
        assert np.isclose(zeta**2, z + 1j * x)         # base point = ζ²
    # ±Ψ are the only preimages of a given base point
    theta = rng.uniform(0, 2 * np.pi)
    target = hopf_r(state(theta))
    hits = [t for t in np.linspace(0, 2 * np.pi, 3601)
            if np.allclose(hopf_r(state(t)), target, atol=1e-3)]
    assert len(hits) <= 3  # 0 and 2π may both appear

def check_density_circle():
    for _ in range(100):
        psi = state(rng.uniform(0, 2 * np.pi))
        rho = np.outer(psi, psi)
        x, z = hopf_r(psi)
        assert np.allclose(rho, (np.eye(2) + x * X + z * Z) / 2)
        assert np.allclose(rho[0], [(1 + z) / 2, x / 2])
        # circle of radius 1/2 centered at (1/2, 0)
        u, v = rho[0, 0], rho[0, 1]
        assert np.isclose((u - 0.5) ** 2 + v**2, 0.25)

def check_born():
    for _ in range(100):
        theta, phi = rng.uniform(0, 2 * np.pi, 2)
        psi = state(theta)
        n = np.array([np.sin(phi), 0, np.cos(phi)])
        plus, minus = state(phi / 2), state(phi / 2 + np.pi / 2)
        assert np.allclose(bloch(plus), n)
        assert np.allclose(bloch(minus), -n)
        r = bloch(psi)
        p_plus = (1 + r @ n) / 2
        p_minus = (1 - r @ n) / 2
        assert np.isclose(p_plus, (plus @ psi) ** 2)
        assert np.isclose(p_minus, (minus @ psi) ** 2)
        assert np.isclose(p_plus, np.cos(theta - phi / 2) ** 2)
        assert np.isclose(p_minus, np.sin(theta - phi / 2) ** 2)

def check_o2_two_to_one():
    # X, Z, H are reflections about 45°, 0°, 22.5°
    for g, phi in [(X, np.pi / 4), (Z, 0), (H, np.pi / 8)]:
        assert np.isclose(np.linalg.det(g), -1)
        assert np.allclose(g, refl2(phi))
        assert np.allclose(base_action(g), refl2(2 * phi))
    # rotations double their angle downstairs
    for _ in range(50):
        theta = rng.uniform(0, 2 * np.pi)
        assert np.allclose(base_action(rot2(theta)), rot2(2 * theta))
        phi = rng.uniform(0, np.pi)
        assert np.allclose(base_action(refl2(phi)), refl2(2 * phi))
    # 2-to-1 with kernel {±I}
    for _ in range(50):
        g = rot2(rng.uniform(0, 2 * np.pi))
        if rng.random() < 0.5:
            g = refl2(rng.uniform(0, np.pi))
        assert np.allclose(base_action(g), base_action(-g))
        trivial = np.allclose(base_action(g), np.eye(2))
        assert trivial == (np.allclose(g, np.eye(2)) or np.allclose(g, -np.eye(2)))

def order(g):
    p = g.copy()
    for k in range(1, 9):
        if np.allclose(p, np.eye(g.shape[0], dtype=g.dtype)):
            return k
        p = p @ g
    raise AssertionError

def check_real_pauli_d4():
    XZ = X @ Z
    assert np.allclose(XZ, rot2(np.pi / 2))
    assert np.allclose(XZ @ XZ, -np.eye(2))
    group = [s * g for s in (1, -1) for g in (np.eye(2), X, Z, XZ)]
    assert len(group) == 8
    for a in group:
        for b in group:
            assert any(np.allclose(a @ b, c) for c in group)
    assert len(closure([X, Z])) == 8
    # five elements of order 2 ⇒ D4
    assert sum(order(g) == 2 for g in group) == 5
    # the complex counterpart {±I, ±iσ} ≅ Q8 has exactly one
    q8 = [s * g for s in (1, -1) for g in (I2, -1j * sx, -1j * sy, -1j * sz)]
    assert len(q8) == 8
    assert sum(order(g) == 2 for g in q8) == 1

def check_real_clifford():
    pauli = [s * g for s in (1, -1) for g in (np.eye(2), X, Z, X @ Z)]

    def normalizes(g):
        return all(any(np.allclose(g @ a @ g.T, b) for b in pauli) for a in pauli)

    # exactly the rotations by multiples of 45° and reflections by 22.5°
    rots = [t for t in np.arange(0, 360, 0.5) if normalizes(rot2(np.radians(t)))]
    assert rots == [45.0 * k for k in range(8)]
    refls = [t for t in np.arange(0, 180, 0.5) if normalizes(refl2(np.radians(t)))]
    assert refls == [22.5 * k for k in range(8)]

    clifford = [rot2(np.radians(t)) for t in rots] \
        + [refl2(np.radians(t)) for t in refls]
    assert len(clifford) == 16
    # generated by H and Z, and mod phase of order 8
    assert len(closure([H, Z])) == 16
    assert len({key(sign_canon(g)) for g in clifford}) == 8

    # Bloch action: the 8 octahedral rotations preserving the y = 0 plane
    actions = {key(np.round(conj_so3(g.astype(complex)), 9)) for g in clifford}
    assert len(actions) == 8
    octa = closure([conj_so3(H), conj_so3(S)])
    assert len(octa) == 24
    assert actions <= {key(np.round(M, 9)) for M in octa}
    assert 24 // 8 == 3
    # downstairs: the symmetry group of the square with vertices ±x, ±z
    squares = {key(base_action(g)) for g in clifford}
    assert len(squares) == 8
    for M in squares:
        N = np.array(M).reshape(2, 2)
        assert np.allclose(np.abs(N) * (np.abs(N) > 0.5), np.abs(N))

def check_s_t_leave_the_plane():
    for U in (S, T):
        assert not np.allclose(U.imag, 0)          # not a real matrix
        M = conj_so3(U)
        assert not np.allclose(M[1, [0, 2]], 0)    # y = 0 plane not preserved
    # S sends the x axis to the y axis
    assert np.allclose(conj_so3(S) @ [1, 0, 0], [0, 1, 0])

if __name__ == "__main__":
    check_bloch_restriction()
    check_double_cover()
    check_density_circle()
    check_born()
    check_o2_two_to_one()
    check_real_pauli_d4()
    check_real_clifford()
    check_s_t_leave_the_plane()
    print("check-07-real-qubit: all checks passed")
